In [ ]:
import pandas as pd
from sympy import gcd
from sympy.ntheory import totient


def index_table(p_root,mod):
    data = {i:0 for i in range(mod) if gcd(mod,i)==1}
       
    root_power = p_root
    for i in range(1,len(data)):
    # v = (p_root**i)%9
        #print(root_power%mod)
        data[root_power%mod] = i

        root_power = root_power * p_root

    
    return data

# data = {i:0 for i in(range(totient(9)))}


def get_ind_func(p_root, mod):
    ind_table = index_table(p_root,mod)
    print(ind_table)
    ind_calc = lambda r: ind_table[r%mod]

    return ind_calc

In [ ]:
from CollatzCITEs import calculate_trajectory
from IPython.display import display, Math
import pandas as pd
import sympy as sym
import re
import dataclasses

class trajectory:
    pass

sym.init_printing()

def calculate_trajectory(l ):

    d = {}
    
    if isinstance(l, list):
        d["cite"] = l
        l = iter(l)
    else:
        d["cite"]=list(l)

    print(d["cite"])
   

    raise_to_pow_2_latex = lambda e: f'2^{e}'


    raise_to_pow_2 = lambda e: 2**(e)
    odds_trajectory=[]
    exponent =next(l,0)
    
        
    num = raise_to_pow_2(exponent)

    latex = raise_to_pow_2_latex(exponent)

    for exponent in l:
        
        # print( num )
        if num % 3 !=1:
            raise ValueError("The trajectory is leading to a non integer!")
        

        num = ((num -1) // 3)
        odds_trajectory.append(num) 
        num = num* raise_to_pow_2(exponent)

        latex = r"\frac{" +latex+ "-1}{3}"
        if(exponent>0):
            latex = latex + "*{"+raise_to_pow_2_latex(exponent)+"}"
    
    latex = f'{num} = {latex}'
    print(odds_trajectory)
    d["odds_trajectory"] = odds_trajectory
    d["latex"] = latex
    d["number"] = num
    return d

def analyze_trajectory(l):

    d = calculate_trajectory(l)


    ind = get_ind_func(2,9)
    data = [d["cite"]]
    data.append(d["odds_trajectory"])
    
    data.append([i%3 for i in d["odds_trajectory"]])
    try:
        data.append([ind(i) for i in d["odds_trajectory"]])
    except:
         data.append([None for i in d["odds_trajectory"]])
    finally:
        display(pd.DataFrame(data, columns=data[0], index=['exponent','odd','mod 3','ind_2']))
    
    
    #print([ind(i) for i in d["odds_trajectory"]])

    display(Math(d["latex"]))

def main():

    user_str = input("Enter exponnents:\n")
    m =re.search(r"(\d+)(?:\s*\,\s*(\d+))+", user_str) 
    if m:
        user_str =  m.group()
        g = ",".split(user_str)
        itr = (int(n.group()) for n in re.finditer(r"\d+", user_str))
        analyze_trajectory(itr)
    else:
        print('invalid input')
            
            # itr = [int(n) for n in re.findall(r"\d+", capture[0])]

# if __name__ == "__main__":
    
#      main()

In [103]:
analyze_trajectory([4, 3, 2, 1, 3, 1, 0])

[4, 3, 2, 1, 3, 1, 0]
[5, 13, 17, 11, 29, 19]
{1: 0, 2: 1, 4: 2, 5: 5, 7: 4, 8: 3}

          4   3   2   1   3   1    0
exponent  4   3   2   1   3   1  0.0
odd       5  13  17  11  29  19  NaN
mod 3     2   1   2   2   2   1  NaN
ind_2     5   2   3   1   1   0  NaN

In [106]:
analyze_trajectory([4, 3, 2, 1, 3, 1,6, 0])

[4, 3, 2, 1, 3, 1, 6, 0]
[5, 13, 17, 11, 29, 19, 405]
{1: 0, 2: 1, 4: 2, 5: 5, 7: 4, 8: 3}

            4     3     2     1     3     1      6    0
exponent  4.0   3.0   2.0   1.0   3.0   1.0    6.0  0.0
odd       5.0  13.0  17.0  11.0  29.0  19.0  405.0  NaN
mod 3     2.0   1.0   2.0   2.0   2.0   1.0    0.0  NaN
ind_2     NaN   NaN   NaN   NaN   NaN   NaN    NaN  NaN

In [109]:
analyze_trajectory([4, 5, 1, 1, 0])

[4, 5, 1, 1, 0]
[5, 53, 35, 23]
{1: 0, 2: 1, 4: 2, 5: 5, 7: 4, 8: 3}

          4   5   1   1    0
exponent  4   5   1   1  0.0
odd       5  53  35  23  NaN
mod 3     2   2   2   2  NaN
ind_2     5   3   3   5  NaN

In [110]:
analyze_trajectory([4, 5, 1, 1,1, 0])

[4, 5, 1, 1, 1, 0]
[5, 53, 35, 23, 15]
{1: 0, 2: 1, 4: 2, 5: 5, 7: 4, 8: 3}

            4     5     1     1     1    0
exponent  4.0   5.0   1.0   1.0   1.0  0.0
odd       5.0  53.0  35.0  23.0  15.0  NaN
mod 3     2.0   2.0   2.0   2.0   0.0  NaN
ind_2     NaN   NaN   NaN   NaN   NaN  NaN